apiVersion: v1
kind: Service
metadata:
  namespace: louper
  name: louper-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31942
      protocol: TCP
  selector:
    app: louper
