apiVersion: v1
kind: Namespace
metadata:
  name: louper-staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: louper-deployment
spec:
  template:
    spec:
      containers:
        - name: louper-container-staging
          image: mark3labs/louper-web:staging-latest
---
apiVersion: batch/v1
kind: Job
metadata:
  name: github-ci
spec:
  template:
    spec:
      containers:
        command:
          - /bin/bash
          - -c
          - |
            apt update && apt install -y ca-certificates
            pkgx install gh
            pkgx install jq
            pkgx install uuidgen
            gh auth login
            export JOB_ID=$(uuidgen)
            echo "{\"job_id\": \"$JOB_ID\" }" | gh workflow run build-and-deploy-staging --repo mark3labs/louper-v3 --ref dev --json
            STATUS="starting"
            while [[ "$STATUS" != "completed" && "$STATUS" != "failure" ]]
            do
              STATUS=$(gh run list --workflow=build-and-deploy-staging --repo mark3labs/louper-v3 --json "status,name" | jq --arg i "build-and-deploy-staging:$JOB_ID" '.[] | select(.name == $i)' | jq -r '.status')
              echo "Job Status: $STATUS"
              sleep 1
            done
