# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: louper-ingress
#   annotations:
#     cert-manager.io/issuer: letsencrypt-louper
# spec:
#   tls:
#     - hosts:
#       - louper.dev
#       secretName: letsencrypt-louper
#   rules:
#     - host: louper.dev
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: louper-service
#                 port:
#                   number: 3000
#   ingressClassName: nginx
- op: replace
  path: /spec/rules/0/host
  value: staging.louper.dev
- op: replace
  path: /spec/rules/0/http/paths/0/backend/service/name
  value: louper-service-staging
- op: replace
  path: '/metadata/annotations/cert-manager.io~1issuer'
  value: letsencrypt-louper-staging
- op: replace
  path: /spec/tls/0/hosts/0
  value: staging.louper.dev
