apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - namespace.yml
  - application.yml
  - jobs.yml
patches:
  - target:
      kind: Deployment
      name: louper-deployment
    path: deployment-patch.yml
  - target:
      kind: Service
      name: louper-service
    path: service-patch.yml

namespace: louper-staging
nameSuffix: -staging
