name: rollout-prod

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */6 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 662138bb-8236-4da5-8c6d-c602fb6eef82

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl rollout restart deployment/louper

      - name: Verify deployment
        run: kubectl rollout status deployment/louper
